version: '2'

services:
  consul:
    image: consul:1.3.1
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    links:
      - cngo-01
      - cngo-02
    networks:
      - sky-net

  cngo-01:
    image: cngo:1.0.0
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - sky-net

  cngo-02:
    image: cngo:1.0.0
    environment:
      - PORT=9080
    ports:
      - "9080:9080"
    networks:
      - sky-net
  
networks:
  sky-net:
    driver: bridge